#Criar tabelas

CREATE TABLE ALUNO(
	NOME VARCHAR(255),
    EMAIL VARCHAR(255),
    DATA_NASCIMENTO DATE,
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY);
    
CREATE TABLE CURSO(
	NOME VARCHAR(255),
    DURACAO VARCHAR(20),
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY);
    
CREATE TABLE ALUNO_CURSO(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_ALUNO INT NOT NULL,
    ID_CURSO INT NOT NULL);  
        
#Mudar o nome
RENAME TABLE ALUNO TO ALUNOS;
RENAME TABLE CURSO TO CURSOS;
RENAME TABLE ALUNO_CURSO TO ALUNOS_CURSOS;

#Apagar tabelas
CREATE TABLE ALUNOS_APAGAR(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY);
    
DROP TABLE ALUNOS_APAGAR    