#Pesquisas

#Pesquisar a tabela toda
SELECT * FROM ALUNOS;

#Pesquisar só a coluna nome na tabela alunos
SELECT NOME FROM ALUNOS;

SELECT * FROM ALUNOS WHERE NOME = "MARIA";

SELECT * FROM ALUNOS WHERE NOME LIKE "%MARIA%";

#Pesquisas com operadores lógicos(>, <, =, <>)

SELECT * FROM ALUNOS WHERE DATA_NASCIMENTO > "1990-01-01";

#Pesquisas com operadores relacionais(and, or)

SELECT * FROM ALUNOS WHERE DATA_NASCIMENTO > "1990-01-01" OR NOME LIKE "%MARIA%";

SELECT * FROM ALUNOS WHERE DATA_NASCIMENTO > "1990-01-01" AND NOME LIKE "%MARIA%";

#Pesquisa combinando tabelas
SELECT ALUNOS.NOME, CURSOS.NOME
FROM ALUNOS, CURSOS, ALUNOS_CURSOS
WHERE ALUNOS.ID = ALUNOS_CURSOS.ID_ALUNO
AND CURSOS.ID = ALUNOS_CURSOS.ID_CURSO;


